#!/bin/bash

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.pgsql 

. /etc/dbconfig-common/fagi-gis-common.conf

# you can set the default database encoding to something else
dbc_pgsql_createdb_encoding="UTF8"

dbc_go fagi-gis-common $@

# echo "Please enter the Superuser of the PostgresSQL installation: "
# read input_variable
# echo "You entered: $input_variable"

# read -e -p "Enter the name of the PostgreSQL Superuser: " -i "postgres" FILEPATH
# echo $FILEPATH

echo "Granting Superuser role to \`$dbc_dbuser' using 'postgres' user needed for creating extentions"

2>/dev/null 1>/dev/null sudo -u postgres psql -c "ALTER ROLE $dbc_dbuser SUPERUSER;"&
2>/dev/null 1>/dev/null sudo -u postgres psql -c "ALTER USER $dbc_dbuser VALID UNTIL 'infinity';"&

wait

echo "Creating PostGIS extentions"

2>/dev/null 1>/dev/null sudo -u postgres psql -d $dbc_dbname -f /usr/share/dbconfig-common/data/fagi-gis-common/install/extend_schema &

wait

echo "PostGIS extentions created"

echo "Superuser role granted"

case "$1" in

  configure)

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac



#DEBHELPER#
