package gr.athenainnovation.imis.fusion.gis.gui;

/**
 * Handles setting of paremeters for {@link gr.athenainnovation.imis.fusion.gis.transformations.ScaleTransformation}.
 * @author Thomas Maroulis
 */
public class ScaleParamsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScaleParamsPanel
     */
    public ScaleParamsPanel() {
        super();
        initComponents();
    }
    
    /**
     *
     * @return scale factor
     */
    public double getScaleFactor() {
        return Double.parseDouble(scaleFactorField.getText());
    }
    
    /**
     *
     * @return true if the left dataset is to be retained by the transformation, false if the right dataset is to be retained
     */
    public boolean isKeepLeftDatasetSet() {
        return keepLeftCheckBox.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keepLeftCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        scaleFactorField = new javax.swing.JTextField();

        keepLeftCheckBox.setSelected(true);
        keepLeftCheckBox.setText("Check to keep left node, uncheck to keep right");
        keepLeftCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keepLeftCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Scale Factor:");

        scaleFactorField.setText("1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(scaleFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(keepLeftCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(scaleFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(keepLeftCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keepLeftCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keepLeftCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keepLeftCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox keepLeftCheckBox;
    private javax.swing.JTextField scaleFactorField;
    // End of variables declaration//GEN-END:variables
}
